version: "3.7"
services:

  php:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - xampp

  db:
    image: mysql:8.0.17
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - "./database/initial_data:/docker-entrypoint-initdb.d"
      - "data:/var/lib/mysql"
    ports:
      - "${DB_PORT}:3306"
    networks:
      - xampp

volumes:
  data:

networks:
  xampp:
